version: '3.7'
services:
  nginx:
    image: nginx:1.13.7
    depends_on:
      - api
    networks:
      - daikon-network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  api:
    image: tm41m/daikon:0.1
    command: gunicorn --bind 0.0.0.0:4000 wsgi:app
    environment:
      SQLALCHEMY_DATABASE_URI: ${DAIKON_SQLALCHEMY_DATABASE_URI}
    logging:
      options:
        max-size: 5m
        max-file: "2"
    volumes:
      - .:/usr/src/daikon
    networks:
      daikon-network:
        aliases:
          - daikon-api
networks:
  daikon-network:
